apiVersion: apps/v1
kind: Deployment
metadata:
  name: doggo
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: doggo
  template:
    metadata:
      labels:
        deployment: doggo
    spec:
      containers:
        - name: doggo-be
          image: golang:1.15.7-alpine3.13 # should be replaced by kustomize
          ports:
            - containerPort: 9090
