name: Go

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v2.3.0

      - name: Test
        run: make ci-coverage

      # Use Nancy for dependencies check: https://github.com/marketplace/actions/nancy-for-github-actions
      - name: WriteGoList
        run: go list -json -m all > go.list

      - name: Dependencies check
        uses: sonatype-nexus-community/nancy-github-action@main
